name: UI-Shared
version: ${project.version}
main: com.ultimateimprovments.shared.UIShared
api-version: '1.21'
depend: [UI-Core]
description: 'Shared utilities: structures, recipes, magnet, radiation, lightning'
author: rizer001
