name: UI-Essentials
version: '1.8.2'
main: com.ultimateimprovments.module.UIEssentials
api-version: '1.21'
description: 'Essential commands: home, teleport, heal, reports, NBT editor, and more'
depend: [UI-Core]
