name: UI-Essentials
version: ${project.version}
main: com.ultimateimprovments.module.UIEssentials
api-version: '26.2'
description: 'Essential commands: home, teleport, heal, reports, NBT editor, and more'
author: rizer001
depend: [UI-Core]
