name: UI-Combat
version: ${project.version}
main: com.ultimateimprovments.combat.UICombat
api-version: '26.2'
depend: [UI-Core]
description: 'Weapons, turrets, and projectile system'
author: rizer001
