name: UI-Other
version: ${project.version}
description: UltimateImprovments — All features add-on
main: com.ultimateimprovments.core.UIOther
api-version: '26.2'
author: rizer001
depend: [UI-Core]
softdepend: [PlaceholderAPI, LuckPerms, Vault]
